First version of the command pattern
MarsBased/patterns pull request #1
Opened 2019-07-25 09:37 UTC by xredo

2019-07-25 14:01 UTC, Dor3nz commented on rails/commands-pattern/app/controllers/users_controller.rb
> +    Users::Create.new.call(user_params).then do |result|
`Users::Create.new(user_params).call` ?

2019-07-25 14:02 UTC, xredo commented on rails/commands-pattern/app/controllers/users_controller.rb
> +    Users::Create.new.call(user_params).then do |result|
😲

Nice catch 👍

2019-07-25 14:08 UTC, ItsGenis approved these changes
As  I already discussed with @oriolbcn during the retreat, I like the approach. :+1:

2019-09-23 11:47 UTC, artero approved these changes

2019-09-23 12:04 UTC, artero commented on rails/commands-pattern/app/commands/users/create.rb
> +  class Create
I think we should use a suffix in the class name like `CreateCommand`, In Rails all classes except models have a suffix and other gems like Keynote uses prefixes in its classes too. Use suffixes could be useful for the project's newbies too.

We could think we only should use suffix if the class have an inheritance but in the Form Objects patter we use Object without inheritance and its classes have suffix too.

2019-09-25 09:13 UTC, dvdgs88 approved these changes

2019-09-25 09:44 UTC, davidgg approved these changes

2019-09-26 11:27 UTC, danigb commented on rails/commands-pattern/app/controllers/users_controller.rb
> +    Users::Create.new(user_params).call.then do |result|
I think `Create` is not a good example (or at least complete). When using `Update` you have to pass two arguments, and then there are two options:

```ruby
Users::Update.new(user).call(params)
```

or 

```ruby
Users::Update.new(user, params).call
```

I don't know which one to use 🤷‍♀️

2019-09-26 11:30 UTC, danigb requested changes
Finally I started to stop worring and liking this pattern 🙄 ... I have doubts about how to pass params to the command (constructor or `call` method or both). I leaved a comment about it

Also I'm not convinced about `then` approach.

Finally, it has to be converted to markdown style pattern 😇

2019-09-26 11:43 UTC, danigb commented on rails/commands-pattern/app/controllers/users_controller.rb
> +    Users::Create.new(user_params).call.then do |result|
I'm not convinced about using `then`. There are two problems:
1. Node developers associate `then` to some kind of asynchronous execution. This is a ruby problem.
2. The code is IMO unnecessarily complex. I prefer to read:

```ruby
result = Users::Create.new(user_params).call
if result.ok
...
```

2019-11-18 15:04 UTC, merged