Form composition pattern
MarsBased/patterns pull request #3
Opened 2019-07-26 12:07 UTC by xredo

This code shows the form composition pattern the way @oriolbcn implemented it in one of our internal projects.

2019-07-29 11:47 UTC, oriolbcn requested changes
a typo and a style consistency change ;)

2019-07-29 11:47 UTC, oriolbcn commented on rails/form-composition-pattern/app/controllers/profiles_controller.rb
> +      organization_attributes: [:name]
`%i(name)`

2019-07-29 11:47 UTC, oriolbcn commented on rails/form-composition-pattern/app/controllers/signups_controller.rb
> +      organization_attributes: [:name]
`%i(name)`

2019-07-29 11:47 UTC, oriolbcn commented on rails/form-composition-pattern/app/forms/signup_form.rb
> +# writing additional logic that the one that the one Rails already provides to us.
`that the one` is repeated twice: `that the one that the one`

2019-07-29 15:16 UTC, xredo commented
@oriolbcn Thanks for the review. Changes applied.

2019-07-29 15:29 UTC, oriolbcn approved these changes

2019-09-23 11:42 UTC, artero approved these changes

2019-09-25 07:35 UTC, ItsGenis approved these changes

2021-03-25 14:40 UTC, merged